services:
  kafka:
    image: docker.io/apache/kafka:4.3.1
    ports:
      - "10.0.0.1:9094:9094"
      - "100.64.0.2:9095:9095"
    environment:
      KAFKA_HEAP_OPTS: "-Xms384m -Xmx384m -XX:MaxMetaspaceSize=96m -XX:ReservedCodeCacheSize=64m"
      KAFKA_JVM_PERFORMANCE_OPTS: >-
        -server
        -Xss512k
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=20
        -XX:InitiatingHeapOccupancyPercent=35
        -XX:+ExplicitGCInvokesConcurrent
        -XX:+UseStringDeduplication
        -XX:+DisableExplicitGC
        -Djava.awt.headless=true
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "DOCKER://0.0.0.0:19094,HOST://0.0.0.0:9094,TAILSCALE://0.0.0.0:9095,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "DOCKER://kafka:19094,HOST://10.0.0.1:9094,TAILSCALE://100.64.0.2:9095"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "DOCKER:PLAINTEXT,HOST:PLAINTEXT,TAILSCALE:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
    volumes:
      - /home/dungeon-master/kafka/data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:19094 || exit 1" ]
      interval: 30s
      timeout: 30s
      start_period: 120s
      retries: 5

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:0c481c0
    ports:
      - '127.0.0.1:1450:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - /etc/kafkaui/dynamic_config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
